name: "Test Django Application"
description: "Action to test Django application running in Docker container"
inputs:
  filename:
    description: "The name of the file to be used in the test"
    required: true
runs:
  using: "composite"
  steps:
    - name: Test health endpoint
      run: echo "Hello!"
      shell: bash